config/routes.rb
Rails.application.routes.draw do
  root 'books#top'
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show, :edit, :update]
   get '/home/about' => 'books#about', as: :about
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true
  validates :body, presence: true,
             length: { maximum: 200 }
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :user_id, presence: true, uniqueness: {scope: :book_id}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  attachment :profile_image
  validates :name, uniqueness: true,
             length: { minimum: 2, maximum: 20 }
  validates :introduction,
             length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
       user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    book_comment = BookComment.new(book_comment_params)
    book_comment.user_id = current_user.id
    book_comment.book_id = book.id
    book_comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def about
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render template: "books/index"
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
    @book_new = Book.new
    @book = Book.find (params[:id])
    @user = @book.user
    @book_comments = @book.book_comments
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find (params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "successfully"
      redirect_to book_path(@book.id)
    else
      render template: "books/edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    #binding.pry
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "successfully"
      redirect_to user_path(@user.id)
    else
      render template: "users/edit"
    end
  end

  def sign_in
    @user = User.new
    render layout: "not_login"
  end


  private

    def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/about.html.erb
 <div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/books/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-8 offset-md-2">
  	 <h1>Editing Book</h1>
  	   <% if @book.errors.any? %>
        <h3>error</h3>
        <%= @book.errors.count %>件のエラーが発生しました
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
    <%= form_with model: @book, local:true do |f| %>
    <div class="form-group">
       <p>Title</p>
       <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group">
       <p>Opinion</p>
       <%= f.text_area :body, class: "form-control" %><br>
    </div>
    <div class="form-group">
       <%= f.submit 'Update Book', class: "btn btn-success" %>
    </div>
    　<% end %>
        <%= link_to "Show", book_path(@book) %>|
        <%= link_to "Back", books_path %>
   </div>
 </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <% if @book.errors.any? %>
       <h3>error</h3>
        <%= @book.errors.count %>件のエラーが発生しました
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <h2 class="mt-3">User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
          </tbody>
        </table>
       <%= link_to "", edit_user_path(current_user), class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user_20911" %>

    <h2 class="mt-3">New book</h2>
    <%= form_with model: @book, local:true do |f| %>
       <p>Title</p>
       <%= f.text_field :title %>
       <p>Opinion</p>
       <%= f.text_area :body %><br>
       <%= f.submit 'Create Book', class: "btn btn-success" %>
    <% end %>
    </div>

   <div class="col-xs-9">
    <h2 class="mt-3">Books</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(book) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(book) do %>
              <%= book.title %>
            <% end %>
          </td>
          <td>
            <%= book.body %>
          </td>
          <td>
           <% if book.favorited_by?(current_user) %>
            <p>
              <%= link_to book_favorites_path(book), method: :delete do %>
                ♥<%= book.favorites.count %>
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to book_favorites_path(book), method: :post do %>
                ♡<%= book.favorites.count %>
              <% end %>
            </p>
           <% end %>
          </td>
          <td>コメント数：<%= book.book_comments.count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2 class="mt-3">User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          </tbody>
        </table>
       <%= link_to "", edit_user_path(@user), class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user_20911" %>

    <h2 class="mt-3">New book</h2>
    <%= form_with model: @book_new, local:true do |f| %>
       <p>Title</p>
       <%= f.text_field :title %>
       <p>Opinion</p>
       <%= f.text_area :body %><br>
       <%= f.submit 'Create Book', class: "btn btn-success" %>
    <% end %>
    </div>

    <div class="col-xs-9">
       <h2 class="mt-3">Book detail</h2>
        <table class="table">
          <tbody>
             <tr>
              <td>
                <%= link_to user_path(@book.user) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %><br><%= @book.user.name %>
                <% end %>
              </td>
              <td><%= link_to @book.title, book_path(@book) %></td>
              <td><%= @book.body %></td>
              <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success" %></td>
              <td><%= link_to "Destroy", book_path(@book), method: :delete, "data-confirm" => "本当に消しますか？", class:"btn btn-danger"%></td>
              <% end %>
              <td>
                <% if @book.favorited_by?(current_user) %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :delete do %>
                      ♥<%= @book.favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to book_favorites_path(@book), method: :post do %>
                      ♡<%= @book.favorites.count %>
                    <% end %>
                  </p>
                <% end %>
              </td>
              <td>コメント数：<%= @book.book_comments.count %></td>
             </tr>
          </tbody>
        </table>

        <table class="comments">
          <tbody>
            <% @book.book_comments.each do |book_comment| %>
            <tr>
              <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %></td>
              <td><%= book_comment.user.name %></td>
              <td><%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <div class="new-comment">
          <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
            <%= f.text_area :comment, rows:'5', class: "form-control" %>
            <%= f.submit "Create Book comment" %>
          <% end %>
      </div>
    </div>
  </div>
</div>

app/views/books/top.html.erb
<div class="container">
 <div class="row">
   <div class="col-md-6 offset-3">
    <h1 class="mt-4">welcom to <i class="fas fa-book"></i>Bookers!!</h1>
    <p>in <i class="fas fa-book"></i>Bookers,</p>
    <p>you can share and exchange your opinions, inpressions, and emotions</p>
    <p>about various books!</p>
   </div>
   <div class="col-md-5 mx-auto">
     <%= link_to "Log in",  new_user_session_path, class: "btn btn-info btn-sm btn-block sign_in" %><br>
     <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
   </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container">
          <h2>Bookers</h2>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to user_path(current_user) do %>
                <i class="fas fa-home nav-link text-dark">Home</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to users_path do %>
                <i class="fas fa-users nav-link text-dark">Users</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to books_path do %>
                <i class="fas fa-book-open nav-link text-dark">Books</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt nav-link text-dark">logout</i>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to root_path do %>
                <i class="fas fa-home nav-link text-dark">Home</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to about_path do %>
                <i class="fas fa-link nav-link text-dark">About</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_registration_path do %>
                <i class="fas fa-user-plus nav-link text-dark">sign up</i>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to new_user_session_path do  %>
                <i class="fas fa-sign-in-alt nav-link text-dark">login</i>
              <% end %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <% if flash[:notice] %>
     <p><%= flash[:notice] %></p>
    <% end %>
    <main>
    <%= yield %>
    </main>
    <footer class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          CopyRight Infratop.inc
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <h2 class="mt-3">User info</h2>
        <% if @user.errors.any? %>
        <h3>error</h3>
        <%= @user.errors.count %>件のエラーが発生しました
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
        <p>Name</p>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control"%>
      </div>
      <div class="form-group">
        <p>Image</p>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>
      <div class="form-group">
        <p>Introduction</p>
         <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", class: "form-control"%>
      </div>
      <div class="form-group">
         <%= f.submit "Update User", class:"btn btn-secondary"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2 class="mt-3">User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
          <tr>
            <th>name</th>
            <th><%= current_user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= current_user.introduction %></th>
          </tr>
          </tbody>
        </table>
     <%= link_to "", edit_user_path(current_user), class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user_20911" %>

    <h2 class="mt-3">New book</h2>
    <%= form_with model: @book, local:true do |f| %>
       <p>Title</p>
       <%= f.text_field :title %>
       <p>Opinion</p>
       <%= f.text_area :body %><br>
       <%= f.submit 'Create Book', class: "btn btn-success" %>
    <% end %>
    </div>

    <div class="col-xs-9">
     <div class="p-3">
      <h2>Users</h2>
      <table class="table">
         <thead>
            <th>image</th>
            <th>name</th>
            <th></th>
         </thead>
         <tbody>
          <% @users.each do |user| %>
           <tr>
            <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user) %></td>
           </tr>
           <% end %>
         </tbody>
      </table>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2 class="mt-3">User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          </tbody>
        </table>
        <%= link_to "", edit_user_path(@user), class:"btn btn-outline-secondary btn-block fas fa-user-cog edit_user_20911" %>

    <h2 class="mt-3">New book</h2>
    <%= form_with model: @book, local:true do |f| %>
       <p>Title</p>
       <%= f.text_field :title %>
       <p>Opinion</p>
       <%= f.text_area :body %><br>
       <%= f.submit 'Create Book', class: "btn btn-success" %>
    <% end %>
    </div>

  <div class="col-xs-9">
    <h2 class="mt-3">Books</h2>
    <table class="table table-hover">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
              <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
          <td>コメント数：<%= @book.book_comments.count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>